#!/bin/sh
# varnish
echo 'install varnish config'
cp ./varnish/default.vcl /etc/varnish/default.vcl
echo 'done.'
echo 'restart varnish'
service varnish restart
echo 'done.'

# php opcache config
echo 'install php opcache config'
cp ./php.d/10-opcache.ini /etc/php.d/10-opcache.ini
echo 'done.'
echo 'restart httpd'
service httpd restart
echo 'done.'

# mysql config
echo 'install my.cnf'
cp my.cnf /etc/my.cnf
echo 'done.'
echo 'restart mysql'
service mysql restart
echo 'done.'

# memcachd config
echo 'install memcached config'
cp memcached /etc/sysconfig/memcached
echo 'done.'
echo 'restart memcachd'
service memcached restart
echo 'done.'
echo 'prepare cache data'
php ../src/setup/setup_memcache.php
echo ''
echo 'done'
